app:
  name: "bbs"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "app.log"
  encoding: "json"
  max_size: 100
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "yngAPDlZZ#4iu3r0f3@ttp5NSuSxsZ6nOzECHV1ghaq6GTyTw3Re!@9P3yvj2"
  dbname: "bbs"
redis:
  host: "127.0.0.1"
  port: 6379
auth:
  jwt_expire: 24